### ISSUE TITLE
Rollup build is outdated

### ISSUE THREAD

**Issue by zeppelin** [chrisyip/closest-element#1]
Could you please publish `v0.0.3` built with a newer version of `rollup-*`? I'm having trouble including it in a bundle that has to run in both Node and browsers, because `Element` is undefined under Node.

The newer build should output something like: `var proto = typeof Element !== 'undefined' ? Element.prototype : {};`

**Comment by chrisyip** [comment]
Thanks, `v0.0.3` published 🎉

**Comment by zeppelin** [comment]
Thank you! :)
